name: Windows

on:
  push:
    branches: ['**']
  pull_request:
  workflow_call:

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows x64
    runs-on: windows-latest

    env:
      SOLUTION_FILE_PATH: .\DarkRadiant.sln
      TESTS_FILE_PATH: .\install\Tests.exe
      BUILD_CONFIGURATION: Release
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject commit hash in version.h
        env:
          VERSION_HEADER_FILE: include\version.h
          SHA: ${{ github.sha }}
        run: |
          $sha = $env:SHA.Substring(0, 7)
          Write-Host "Writing $sha to $env:VERSION_HEADER_FILE"
          $replaced = Get-Content $env:VERSION_HEADER_FILE | % {
            if ($_ -match '#define RADIANT_VERSION "((\d+.\d+.\d+)([\w\d]*))"') {
              $_.Replace($matches[1], $matches[2] + "_rev$sha")
            } else { $_ }
          }
          $replaced | Out-File $env:VERSION_HEADER_FILE
        shell: powershell

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: >
          msbuild /m
          /p:Configuration=${{ env.BUILD_CONFIGURATION }}
          /p:Platform=x64
          /maxcpucount:4
          /nodeReuse:false
          /p:UseSharedConfiguration=false
          ${{ env.SOLUTION_FILE_PATH }}

      - name: Install Mesa openGL Drivers
        env:
          UNIT_TEST_MESA_DRIVER_URL: https://github.com/codereader/DarkRadiant_WinDeps/releases/download/3.0.0/unit_test_mesa_driver-x64-20.1.8.7z
        run: |
          Write-Host ("Downloading Mesa driver package from {0}..." -f $env:UNIT_TEST_MESA_DRIVER_URL)
          $outFile = ".\install\unit_test_mesa_driver-x64.7z"
          Invoke-WebRequest $env:UNIT_TEST_MESA_DRIVER_URL -OutFile $outFile
          Write-Host ("Unpacking {0}..." -f $outFile)
          & .\tools\7z\7za.exe x $outFile -o".\install\"
          Get-ChildItem .\install\OpenGL32.dll
        shell: powershell

      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1.3

      - name: Run Unit Tests
        run: |
          FOR /F "tokens=* USEBACKQ" %%g IN (`powershell -Command "(Get-ChildItem -Recurse -Path 'C:\Program Files\Microsoft Visual Studio\' -Filter "GoogleTestAdapter.TestAdapter.dll" -ErrorAction SilentlyContinue).DirectoryName"`) do (SET "GTEST_ADAPTER_PATH=%%g")
          echo Test Adapter Path resolved to: %GTEST_ADAPTER_PATH%
          vstest.console.exe ${{ env.TESTS_FILE_PATH }} /Platform:x64 /Logger:trx /TestAdapterPath:"%%GTEST_ADAPTER_PATH%%"
        shell: cmd

      - name: Generate portable package
        run: |
          del ..\..\install\OpenGL32.dll
          powershell -ExecutionPolicy ByPass .\compile_release_package.ps1 -Platform x64 -SkipBuild -GenerateSetupPackage:$false -GeneratePortablePackage:$false -OutputFolder ..\..\PortablePackage\
        shell: cmd
        working-directory: .\tools\scripts

      - name: Upload portable package
        uses: actions/upload-artifact@v4
        with:
          name: darkradiant-windows-x64
          path: |
            tools/scripts/DarkRadiant_install.x64/**/*
            !tools/scripts/DarkRadiant_install.x64/**/*.pdb

      - name: Upload PDB files
        uses: actions/upload-artifact@v4
        with:
          name: darkradiant-windows-x64-pdb
          path: tools/scripts/DarkRadiant_install.x64/**/*.pdb

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: TestResults\*.trx
